# Generated by Django 5.2.10 on 2026-08-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('referrer_host', models.CharField(blank=True, max_length=255)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], default='other', max_length=20)),
                ('visitor_key', models.CharField(db_index=True, max_length=32)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_p_timesta_835321_idx'), models.Index(fields=['path', 'timestamp'], name='analytics_p_path_51c7b7_idx'), models.Index(fields=['visitor_key', 'timestamp'], name='analytics_p_visitor_25cc91_idx')],
            },
        ),
    ]
